name: Manual Deploy to Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 1.0.0)'
        required: true
        type: string
      skip_tests:
        description: 'Skip tests during deployment'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Validate version format
      run: |
        VERSION="${{ github.event.inputs.version }}"
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Version must be in format X.Y.Z (e.g., 1.0.0)"
          exit 1
        fi
        echo "Deploying version: $VERSION"
        
    - name: Update version in pom.xml
      run: |
        VERSION="${{ github.event.inputs.version }}"
        ./mvnw versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
        
    - name: Run tests
      if: ${{ !github.event.inputs.skip_tests }}
      run: ./mvnw clean test
      
    - name: Import GPG signing key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Configure Maven for OSSRH
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>ossrh</id>
              <username>${{ secrets.OSSRH_USERNAME }}</username>
              <password>${{ secrets.OSSRH_PASSWORD }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>ossrh</id>
              <activation>
                <activeByDefault>true</activeByDefault>
              </activation>
              <properties>
                <gpg.executable>gpg</gpg.executable>
                <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
              </properties>
            </profile>
          </profiles>
        </settings>
        EOF
        
    - name: Deploy to Maven Central
      run: |
        if [[ "${{ github.event.inputs.skip_tests }}" == "true" ]]; then
          ./mvnw clean deploy -P release -DskipTests
        else
          ./mvnw clean deploy -P release
        fi
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-central-artifacts-${{ github.event.inputs.version }}
        path: |
          target/*.jar
          target/*.pom
          target/*.asc
        retention-days: 30
        
    - name: Summary
      run: |
        echo "🎉 Successfully deployed version ${{ github.event.inputs.version }} to Maven Central!"
        echo ""
        echo "📦 Artifacts uploaded:"
        echo "  - JAR file with compiled classes"
        echo "  - Sources JAR"
        echo "  - Javadoc JAR"
        echo "  - POM file"
        echo "  - GPG signatures for all artifacts"
        echo ""
        echo "⏳ Note: It may take up to 2 hours for the artifacts to appear in Maven Central search."
        echo "🔗 Check release status: https://s01.oss.sonatype.org/"
